### ISSUE TITLE
cannot do a clean/new install

### ISSUE THREAD

**Issue by davie-robertson** [thepassle/create-lit-app#5]
I think the new version of Babel is causing the install to break:

```
npm install --global create-lit-app

> create-lit-app@1.0.0 postinstall /Users/davidrobertson/.nvm/versions/node/v8.11.4/lib/node_modules/create-lit-app
> node utils/generate-helpers.js && npm run build && npm run --silent greeting

module.js:549
    throw err;
    ^

Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/davidrobertson/development/create-lit-app/utils/generate-helpers.js:3:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by thepassle** [comment]
Should be fixed, try updating create-lit-app to 1.1.0 :)

Please let me know if the problem persists

**Comment by davie-robertson** [comment]
ok, how should I do that since I'm using npm to try and install it?

**Comment by thepassle** [comment]
Try `npm install -g create-lit-app@1.1.0`
